name = "McMods"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a0d6571703d1e4a9a377086d2461457438dec6b92b425a2734bc8903f39193c"

[versions]
fabric = "0.14.9"
minecraft = "1.19.1"

[options]
acceptable-game-versions = ["1.19.1", "1.19"]
