name = "McMods"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93ff2198124ff60a96fe018b74e8f417ec7d3af2bd36745c07f23d9896ee9a6b"

[versions]
fabric = "0.14.9"
minecraft = "1.19.1"

[options]
acceptable-game-versions = ["1.19.1", "1.19"]
