name = "McMods"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "24bc6cfdfa3d7043f04410fd9b75b96a08ab7f9a842c406307e74187cbb7dbd8"

[versions]
fabric = "0.14.9"
minecraft = "1.19.1"

[options]
acceptable-game-versions = ["1.19.1", "1.19"]
