name = "Lithium"
filename = "lithium-fabric-mc1.19.1-0.8.3.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/gvQqBUqZ/versions/mc1.19.1-0.8.3/lithium-fabric-mc1.19.1-0.8.3.jar"
hash-format = "sha512"
hash = "a3b623b4c14f6ba46d1486ffb3d1ba3174e3317b419b2ddfdf7bb572244e706d2e0a37bdce169c94455bec00fd107530ba78d7e611162a632cc6950e6a625433"

[update]
[update.modrinth]
mod-id = "gvQqBUqZ"
version = "ZRR9yqHD"
